use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {

  // do stuff

    Ok(())
}
